export enum NotificationType {
  EXPENSE_APPROVED = "EXPENSE_APPROVED",
  EXPENSE_REJECTED = "EXPENSE_REJECTED",
  APPROVAL_REQUIRED = "APPROVAL_REQUIRED",
  BUDGET_ALERT = "BUDGET_ALERT",
  INVITATION = "INVITATION",
  SYSTEM_ALERT = "SYSTEM_ALERT",
}
