/**
 * Standard audit action types for expense tracker application
 */
export enum AuditActionType {
  // User Actions
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  USER_DELETED = "USER_DELETED",
  USER_LOGIN = "USER_LOGIN",
  USER_LOGOUT = "USER_LOGOUT",
  USER_PASSWORD_CHANGED = "USER_PASSWORD_CHANGED",

  // Workspace Actions
  WORKSPACE_CREATED = "WORKSPACE_CREATED",
  WORKSPACE_UPDATED = "WORKSPACE_UPDATED",
  WORKSPACE_DELETED = "WORKSPACE_DELETED",
  WORKSPACE_MEMBER_ADDED = "WORKSPACE_MEMBER_ADDED",
  WORKSPACE_MEMBER_REMOVED = "WORKSPACE_MEMBER_REMOVED",
  WORKSPACE_MEMBER_ROLE_CHANGED = "WORKSPACE_MEMBER_ROLE_CHANGED",

  // Expense Actions
  EXPENSE_CREATED = "EXPENSE_CREATED",
  EXPENSE_UPDATED = "EXPENSE_UPDATED",
  EXPENSE_DELETED = "EXPENSE_DELETED",
  EXPENSE_SUBMITTED = "EXPENSE_SUBMITTED",
  EXPENSE_APPROVED = "EXPENSE_APPROVED",
  EXPENSE_REJECTED = "EXPENSE_REJECTED",
  EXPENSE_REIMBURSED = "EXPENSE_REIMBURSED",

  // Receipt Actions
  RECEIPT_UPLOADED = "RECEIPT_UPLOADED",
  RECEIPT_DELETED = "RECEIPT_DELETED",
  RECEIPT_OCR_PROCESSED = "RECEIPT_OCR_PROCESSED",

  // Budget Actions
  BUDGET_CREATED = "BUDGET_CREATED",
  BUDGET_UPDATED = "BUDGET_UPDATED",
  BUDGET_DELETED = "BUDGET_DELETED",
  BUDGET_THRESHOLD_EXCEEDED = "BUDGET_THRESHOLD_EXCEEDED",

  // Category Actions
  CATEGORY_CREATED = "CATEGORY_CREATED",
  CATEGORY_UPDATED = "CATEGORY_UPDATED",
  CATEGORY_DELETED = "CATEGORY_DELETED",

  // Approval Workflow Actions
  APPROVAL_WORKFLOW_CREATED = "APPROVAL_WORKFLOW_CREATED",
  APPROVAL_WORKFLOW_UPDATED = "APPROVAL_WORKFLOW_UPDATED",
  APPROVAL_REQUEST_CREATED = "APPROVAL_REQUEST_CREATED",
  APPROVAL_REQUEST_APPROVED = "APPROVAL_REQUEST_APPROVED",
  APPROVAL_REQUEST_REJECTED = "APPROVAL_REQUEST_REJECTED",

  // Cost Allocation Actions
  DEPARTMENT_CREATED = "DEPARTMENT_CREATED",
  DEPARTMENT_UPDATED = "DEPARTMENT_UPDATED",
  COST_CENTER_CREATED = "COST_CENTER_CREATED",
  COST_CENTER_UPDATED = "COST_CENTER_UPDATED",
  PROJECT_CREATED = "PROJECT_CREATED",
  PROJECT_UPDATED = "PROJECT_UPDATED",
  EXPENSE_ALLOCATED = "EXPENSE_ALLOCATED",

  // Policy Actions
  POLICY_CREATED = "POLICY_CREATED",
  POLICY_UPDATED = "POLICY_UPDATED",
  POLICY_VIOLATION_DETECTED = "POLICY_VIOLATION_DETECTED",

  // Report Actions
  REPORT_GENERATED = "REPORT_GENERATED",
  REPORT_EXPORTED = "REPORT_EXPORTED",

  // System Actions
  SYSTEM_CONFIG_CHANGED = "SYSTEM_CONFIG_CHANGED",
  DATA_EXPORTED = "DATA_EXPORTED",
  DATA_IMPORTED = "DATA_IMPORTED",
}

/**
 * Entity types that can be audited
 */
export enum AuditEntityType {
  USER = "USER",
  WORKSPACE = "WORKSPACE",
  EXPENSE = "EXPENSE",
  RECEIPT = "RECEIPT",
  BUDGET = "BUDGET",
  CATEGORY = "CATEGORY",
  APPROVAL_WORKFLOW = "APPROVAL_WORKFLOW",
  APPROVAL_REQUEST = "APPROVAL_REQUEST",
  DEPARTMENT = "DEPARTMENT",
  COST_CENTER = "COST_CENTER",
  PROJECT = "PROJECT",
  POLICY = "POLICY",
  REPORT = "REPORT",
  NOTIFICATION = "NOTIFICATION",
  SYSTEM = "SYSTEM",
}
